#!/bin/bash

echo "-----------------"
echo "| otoressl by UG |"
echo "------------------------------"
echo "| copyright belongs to Allah |"
echo "------------------------------"

## Checking dependencies
echo "checking dependencies.."
echo ""
if ! which which; then
  echo "please install which package and then reinstall otoressl.."
  echo "example (centos): yum install which -y"
  echo "exiting.."
  exit 1
fi

echo ""
echo "installing otoressl.."
echo ""

## Create otoressl dir
if [[ ! -d /etc/otoressl ]]; then
  mkdir /etc/otoressl
fi

## Download config
if ! curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/v1.2.1/config; then
echo ""
echo "otoressl installation failed.."
echo "please retry.."
exit 1
fi

## Download script otoressl
if ! curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/v1.2.1/otoressl; then
echo ""
echo "otoressl installation failed.."
echo "please retry.."
exit 1
fi
chmod +x /bin/otoressl

echo ""
echo "otoressl installed successfully.."
