#!/bin/bash

echo "-----------------"
echo "| otoressl by UG |"
echo "------------------------------"
echo "| copyright belongs to Allah |"
echo "------------------------------"

echo ""
echo "checking dependency.."
CURL=$(which curl)
if [[ $CURL == "" ]]; then
echo ""
echo "cannot find curl, please insall curl.."
exit 1
fi

echo ""
echo "installing otoressl.."
echo ""

## Create otoressl dir
if [[ ! -d /etc/otoressl ]]; then
  mkdir /etc/otoressl
fi

## Download config
if ! curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/v1.1.1/config; then
echo ""
echo "otoressl installation failed.."
echo "please retry.."
exit 1
fi

## Download script otoressl
if ! curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/v1.1.1/otoressl; then
echo ""
echo "otoressl installation failed.."
echo "please retry.."
exit 1
fi
chmod +x /bin/otoressl

echo ""
echo "otoressl installed successfully.."
