#!/bin/bash

echo "-----------------"
echo "| otoressl by UG |"
echo "------------------------------"
echo "| copyright belongs to Allah |"
echo "------------------------------"

echo ""
echo "installing otoressl.."
echo ""

## Create otoressl dir
mkdir /etc/otoressl

## Download config
curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/main/config

## Download script otoressl
curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/main/otoressl
chmod +x /bin/otoressl

## 
curl -o /bin/send-notify https://nextcloud.cloud.untad.ac.id/s/34Hc6MsrwpC6CjF/download/send-notify
chmod +x /bin/send-notify

echo ""
echo "otoressl installed successfully.."
