#!/bin/bash

echo "-----------------"
echo "| otoressl by UG |"
echo "------------------------------"
echo "| copyright belongs to Allah |"
echo "------------------------------"

echo ""
echo "installing otoressl.."
echo ""

## Create otoressl dir
if [[ ! -d /etc/otoressl ]]; then
  mkdir /etc/otoressl
fi

## Download config
curl -o /etc/otoressl/config https://raw.githubusercontent.com/deadlyug/otoressl/v1.0.1/config

## Download script otoressl
curl -o /bin/otoressl https://raw.githubusercontent.com/deadlyug/otoressl/v1.0.1/otoressl
chmod +x /bin/otoressl

echo ""
echo "otoressl installed successfully.."
