#!/bin/bash
OS=$(hostnamectl | grep "Operating System" | awk '{print $3}')
validDay=$(certbot certificates | grep Expiry | awk '{print $6}')

echo ""
echo "Mengecek tanggal expire sertifikat ssl.."
source ./config

if [[ $validDay < 30 ]]; then
  if [[ $TOKEN_BOT_TELEGRAM && $ID_BOT_TELEGRAM != "" ]]; then
  curl -s -X POST https://api.telegram.org/bot${TOKEN_BOT_TELEGRAM}/sendMessage -d chat_id=${ID_BOT_TELEGRAM} -d text="NOTIF SSL @$(cat /etc/hostname)

Renewing certificate..
" &>/dev/null &
  fi

  echo "Renewing certificate.."

  case $OS in
    "Arch")
      ;;
    "Ubuntu")
      ;;
    "CentOS")
      if [[ $2 == "--disable-firewall" ]]; then
        case $3 in
          "iptables")
            echo "menon-aktifkan firewall.."
            if systemctl stop iptables; then
              echo "berhasil menon-aktifkan firewall.."
            fi
            ;;
          "firewalld")
            echo "menon-aktifkan firewall.."
            if systemctl stop firewalld; then
              echo "berhasil menon-aktifkan firewall.."
            fi
            ;;
        esac
      fi
      ;;
  esac

  if $(which certbot) renew; then
    if [[ $TOKEN_BOT_TELEGRAM && $ID_BOT_TELEGRAM != "" ]]; then
    curl -s -X POST https://api.telegram.org/bot${TOKEN_BOT_TELEGRAM}/sendMessage -d chat_id=${ID_BOT_TELEGRAM} -d text="NOTIF SSL $(cat /etc/hostname)

Success! certificate renewed..
menghitung hari untuk dibuatkan cronjob/automatic renew certificate...
" &>/dev/null &
    fi

    echo "Success! certificate renewed..
menghitung hari untuk dibuatkan cronjob/automatic renew certificate...
"
  fi
else
  echo "belum memasuki waktu yang pas untuk renew certificate..."
  echo "menghitung hari untuk dibuatkan cronjob/automatic renew certificate..."
fi

isCrontab=$(which crontab)

if [[ $isCrontab == "" ]]; then
  
  case $OS in
    "Arch")
      sudo pacman -Syyy cronie
      systemctl enable --now cronie
      ;;
    "Ubuntu")
      apt-get update && apt-get install cron
      systemctl enable --now cron
      ;;
    "CentOS")
      yum update && yum install cronie
      systemctl enable --now cronie
      if [[ $2 == "--disable-firewall" ]]; then
        case $3 in
          "iptables")
            systemctl stop firewalld
            ;;
          "firewalld")
            systemctl stop firewalld
            ;;
        esac
      fi
      ;;
  esac
  
fi

crontab -l | sed 's/.*otoressl.*//' | crontab -
crontab -l | sed '/^$/d'| crontab -

renewDay="$(($validDay - 10))"

month=$(date --date="+$renewDay days" +%-m)
day=$(date --date="+$renewDay days" +%-d)

{ crontab -l; echo "0 9 $day $month * source $(pwd)/otoressl"; } | crontab -

if [[ $TOKEN_BOT_TELEGRAM && $ID_BOT_TELEGRAM != "" ]]; then
  curl -s -X POST https://api.telegram.org/bot${TOKEN_BOT_TELEGRAM}/sendMessage -d chat_id=${ID_BOT_TELEGRAM} -d text="NOTIF SSL $(cat /etc/hostname)

berhasil membuat cronjob untuk otomisasi renew certificate..
" &>/dev/null &
fi
echo ""
echo "berhasil membuat cronjob untuk otomisasi renew certificate.."
crontab -l

case $OS in
  "Arch")
    ;;
  "Ubuntu")
    ;;
  "CentOS")
    if [[ $2 == "--disable-firewall" ]]; then
      case $3 in
        "iptables")
          echo "mengaktifkan kembali firewall.."
          if systemctl start iptables; then
            echo "berhasil mengaktifkan firewall.."
          fi
          ;;
        "firewalld")
          echo "mengaktifkan kembali firewall.."
          if systemctl start firewalld; then
            echo "berhasil mengaktifkan firewall.."
          fi
          ;;
      esac
    fi
    ;;
esac

